# Hands-on 01 - D01

## Escalar

No matlab, um escalar é um variável com apenas uma linha e uma coluna. É uma variavel simples, usada para manipular equações algebricas simples.

In [1]:
x=1;
y=2;
z=x+y


z =

     3



## Vetor

Vetor já é uma variável com mais de uma linha ou mais de uma coluna. Um vetor tem vários propositos, um deles é plotar gráfico x por y. 

In [2]:
y=1:5
x=ones(1,5)


y =

     1     2     3     4     5


x =

     1     1     1     1     1



## Matriz

Matriz é uma variável com mais de uma linha e mais de uma coluna. Uma matriz tem função de processar vários elementos, retornando também vários elementos. 

In [4]:
A = [1 2; 3 4]
B = eye(3,3)


A =

     1     2
     3     4


B =

     1     0     0
     0     1     0
     0     0     1



## String

São variáveis usadas para rotular saídas, são matrizes cujos elementos são caractéres. 

In [7]:
nome = 'Victor'
frutas = ['laranja', 'goiaba', 'banana', 'abacaxi']


nome =

Victor


frutas =

laranjagoiababananaabacaxi

